--LAB 4 JOIN
-- LIST STAFF FIRST AND LAST NAMES ALONG WITH BRANCH CITY
-- BY USING PREFIX
SELECT FNAME, LNAME, BRANCH.BRANCHNO,CITY
FROM STAFF, BRANCH
WHERE STAFF.BRANCHNO = BRANCH.BRANCHNO;

-- BY USING Table aliases 
SELECT FNAME, LNAME, B.BRANCHNO,CITY
FROM STAFF S, BRANCH B
WHERE S.BRANCHNO = B.BRANCHNO;

-- LIST STAFF FIRST AND LAST NAMES ALONG WITH BRANCH CITY. DISPLAY ONLY WHERE SALARIES > 10000
SELECT FNAME, LNAME, B.BRANCHNO,CITY
FROM STAFF S, BRANCH B
WHERE S.BRANCHNO = B.BRANCHNO
AND SALARY > 10000;

-- USING NATURAL JOIN
SELECT FNAME, LNAME, BRANCHNO,CITY
FROM STAFF NATURAL JOIN BRANCH
WHERE SALARY > 10000;

-- 	List names of all clients who have viewed a property along with any comment supplied.

SELECT * FROM client;
SELECT * FROM viewing;

-- OLD-STYLE JOIN
SELECT FNAME,LNAME, PROPERTYNO, VCOMMENT
FROM CLIENT C, VIEWING V
WHERE C.CLIENTNO = V.CLIENTNO;

--NATURAL JOIN
SELECT FNAME,LNAME, PROPERTYNO, VCOMMENT
FROM CLIENT NATURAL JOIN VIEWING ;

-- JOIN ---- ON
SELECT FNAME,LNAME, PROPERTYNO, VCOMMENT
FROM CLIENT C JOIN VIEWING V
ON C.CLIENTNO = V.CLIENTNO;


--List names of all clients who have viewed a property along with any comment supplied, 
-- AND include the number of rooms FOR EACH PROPERTY.
SELECT FNAME, LNAME, P.PROPERTYNO, C.CLIENTNO, VCOMMENT,ROOMS
FROM CLIENT C, VIEWING V, PROPERTYFORRENT P
WHERE C.CLIENTNO = V.CLIENTNO
AND V.PROPERTYNO = P.PROPERTYNO;

-- NATURAL JOIN
SELECT FNAME, LNAME, PROPERTYNO, CLIENTNO, VCOMMENT,ROOMS
FROM CLIENT NATURAL JOIN VIEWING NATURAL JOIN PROPERTYFORRENT ;

-- JOIN --- ON
SELECT FNAME, LNAME, P.PROPERTYNO, C.CLIENTNO, VCOMMENT,ROOMS
FROM CLIENT C JOIN VIEWING V 
ON C.CLIENTNO = V.CLIENTNO 
JOIN  PROPERTYFORRENT P 
ON V.PROPERTYNO = P.PROPERTYNO;

-- USING LEFT JOIN
SELECT C.CLIENTNO, FNAME, V.CLIENTNO, VCOMMENT
FROM CLIENT C LEFT JOIN VIEWING V
ON C.CLIENTNO = V.CLIENTNO;
















