CREATE TABLE STUDENT 
    (SID CHAR(9) PRIMARY KEY, --here no student number will be longer than 9 characters
    SNAME VARCHAR (30) NOT NULL, --we assume that no student name will have more than 30 characters
    DOB DATE);
    
    
CREATE TABLE COURSE
    (CID CHAR(5) CONSTRAINT COURSE_CID_PK PRIMARY KEY, --ALWAYS name your constraints
    TITLE VARCHAR (30) NOT NULL,
    CREDIT NUMBER(1) CONSTRAINT COURSE_CREDIT_CK CHECK (CREDIT >= 1 AND CREDIT <= 4));


CREATE TABLE ENROLLMENT
    (SID CHAR(9),
    CID CHAR(5),
    GRADE NUMBER(4,1) CONSTRAINT ENROLL_GRADE_CK CHECK(GRADE >= 0 AND GRADE <= 100),
    CONSTRAINT ENROLL_SID_CID_PK PRIMARY KEY(SID, CID),
    CONSTRAINT ENROLL_SID_FK FOREIGN KEY(SID) REFERENCES STUDENT,
    CONSTRAINT ENROLL_CID_FK FOREIGN KEY(CID) REFERENCES COURSE);
    --we use the references keyword to link student table to enrollment table,
    --meaning that if we were to try to enroll a student that doesn't exist in the
    --student table, we'd get a problem. It would not enroll.
    
ALTER TABLE STUDENT 
    ADD EMAIL_ADD VARCHAR(20) UNIQUE; --ADDING EMAIL_ADD COMLUMN

ALTER TABLE STUDENT
    MODIFY SNAME VARCHAR(50); --MODIFYING SIZE OF SNAME
    
ALTER TABLE STUDENT
    DROP COLUMN EMAIL_ADD; --REMOVING EMAIL_ADD COLUMN

ALTER TABLE STUDENT
    RENAME COLUMN SNAME TO STUDENT_NAME; --RENAMING COLUMN
    
ALTER TABLE COURSE
    ADD CONSTRAINT COURSE_TITLE_UQ UNIQUE(TITLE); --ADDING CONSTRAINT
    
ALTER TABLE COURSE
    DROP CONSTRAINT COURSE_TITLE_UQ; --DROPPING A CONSTRAINT
    
DROP TABLE COURSE; --TIHS DOES NOT WORK BECAUSE IT HAS PK, FK IN DIFF TABLES
DROP TABLE COURSE CASCADE CONSTRAINTS; --THIS IS WHAT WE HAVE TO DO
DROP TABLE STUDENT CASCADE CONSTRAINTS;

-- OR
ALTER TABLE ENROLLMENT
DROP CONSTRAINT ENROL_CID_FK;

DROP TABLE COURSE;

--also to check constraints:
--SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
--FROM USER_CONSTRAINTS;







